steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - auth
      - configure-docker
      - asia-southeast2-docker.pkg.dev
      - --quiet

  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'asia-southeast2-docker.pkg.dev/d-04-488904/backend-repo/backend:latest',
        '.'
      ]

  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'asia-southeast2-docker.pkg.dev/d-04-488904/backend-repo/backend:latest'
      ]

images:
  - 'asia-southeast2-docker.pkg.dev/d-04-488904/backend-repo/backend:latest'

options:
  logging: CLOUD_LOGGING_ONLY
